name: main

on:
  pull_request:
  push:
    branches:
      - main
env:
  DOCKER_IMAGE: username/repo

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

      - name: Test
        run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt -json ./... > test.json

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.7.0
        with:
          test-results: test.json

      - name: Build and push to CR
        if: github.event_name == 'push'
        uses: chuhlomin/actions/docker-build-push@main
        with:
          username: username
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ env.DOCKER_IMAGE }}
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
      
      # - name: Build and push to CR
      #   uses: chuhlomin/actions/docker-build-push@main
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.PKG_TOKEN }}
      #     image_name: ${{ env.DOCKER_IMAGE }}
      #     tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Test action
        uses: ./ # Uses an action in the root directory
        with:
          key: value
